language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "4.4"
  - "4"
  - "5"
  - "6"
  - "7"

notifications:
  email: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
